#!/usr/bin/env python3
"""Build audited UTF-8 Apple strings resources; no network or runtime translation."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'scripts/localization'
LANGUAGES = ['zh-Hans', 'zh-Hant', 'en', 'ja', 'ko', 'es', 'fr', 'de', 'it', 'pt-BR', 'ru', 'ar', 'hi', 'id', 'th', 'vi']
keys = json.loads((SOURCE / 'source_keys.json').read_text())
translations = {}
for number, line in enumerate((SOURCE / 'catalog.tsv').read_text().splitlines(), 1):
    if not line.strip(): continue
    fields = line.split('|')
    assert len(fields) == 16, (number, len(fields))
    source = keys[int(fields[0])] if fields[0].isdigit() else fields[0]
    assert source not in translations, ('Duplicate source', source)
    assert all(fields[1:]), ('Empty translation', source)
    tokens = re.compile(r"%(?:[0-9]+\$)?[+0-9.]*[@df]")
    for value in fields[1:]:
        assert len(tokens.findall(value)) == len(tokens.findall(source)), ('Format mismatch', source, value)
        assert all(token == '%@' for token in tokens.findall(value)), ('Use string substitutions for captured values', source)
    translations[source] = [source] + [v.replace(r"\n", "\n") for v in fields[1:]]

# Technical diagnostics remain intact in stored capture notes and logs. Their
# localized presentation uses concise, actionable categories without claiming
# an original exists when the source only says capture failed.
aliases = {}
def alias(target, *indices):
    target = keys[target] if isinstance(target, int) else target
    assert target in translations, target
    for index in indices:
        source = keys[index]
        assert source not in translations and source not in aliases, source
        aliases[source] = target

alias('暂时无法使用相机，请稍后重试。', 0,125,128,135,145,151,152,153,154,168,171)
alias('当前镜头不支持此录制规格，请选择较低规格。', 1,122,123,133,142,143,149)
alias('拍摄未能完成，请重试。已有原片仍保留在 App 中。', 2,3,4,6,172,173,190)
alias(7, 8,9,10,11)
alias('声音暂时不可用，请检查麦克风权限后重试。', 5,163,164,165)
alias('锁屏素材暂未导入，原文件已保留。请解锁后重试。', 13,14,16,17,18)
alias('关于 ArkCam',52)
alias(37,54)
alias(29,64)
alias(233,68)
alias(234,69)
alias('Live Photo 暂不可用，静态照片仍会保留。',70,157,193,194,324,327,328,330,337)
alias('ArkCam · iOS 预览版 0.1',102)
translations[keys[103]] = ['ArkCam'] * 16
alias('请解锁 iPhone 后重试。',116,207,349)
alias('原片不完整，无法合成；已有素材仍保留在回忆中。',118,159,162,191,192,220,261,283,286,287,305)
alias('当前镜头的闪光灯或补光暂不可用。',124,247,248)
alias('此设备暂不支持当前相机组合，请使用单摄模式。',127,131,132,134,136,144)
alias('切换未完成，已恢复原模式。',126)
alias('拍摄已中断，已保留能够保存的原片，请在回忆中查看。',129,130,166,167,169,170,344)
alias('倍率暂时无法调整，请重试。',137,138,139,140,141)
alias('对焦或曝光暂时无法调整，请重试。',146,147,148)
alias('Live Photo 可以保存，但这次没有声音。',155,156,329)
alias(66,177)
alias(67,178)
alias(60,219,223)
alias('保存尚未完成，请重试。原片仍保留在 App 中。',222,276,284,285,288,291,292,293,296,297,298,299,300,301,303,331,332,333,334,335,336,338,339,340,341,342)
alias('请在系统设置允许 ArkCam 添加照片，然后重试。原片仍已保留。',224,225,307)
alias(318,230,326)
alias(73,232)
alias(240,245)
alias(239,246)
alias(259,260)
alias(273,274,275)
alias(7,289,290,294,295,302)
alias(315,316,317)
alias('拍摄已中断，已保留能够保存的原片，请在回忆中查看。',325)
alias('无法读取回忆，请重新打开 App。',343)
alias('使用相机记录眼前的画面，也支持同时记录镜头后面的你。',351,352)
for source, target in aliases.items(): translations[source] = [source] + translations[target][1:]
# URLs, output basenames, and metadata software identifiers are not UI prose.
excluded = {218,304,308,309,310}
assert not [(i,k) for i,k in enumerate(keys) if i not in excluded and k not in translations]

privacy = {
 'NSCameraUsageDescription': '使用相机记录眼前的画面，也支持同时记录镜头后面的你。',
 'NSMotionUsageDescription': '读取手机倾斜状态，在取景时显示水平仪。',
 'NSMicrophoneUsageDescription': '使用麦克风为视频和 Live Photo 记录声音。',
 'NSLocationWhenInUseUsageDescription': '为照片和视频记录拍摄位置，方便日后回看。',
 'NSPhotoLibraryAddUsageDescription': '按你的设置自动保存照片、实况照片和视频到系统相册，原片保留在 App 中。',
}
def write_strings(path, values):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('// Generated by scripts/generate_localizations.py. Edit scripts/localization/catalog.tsv.\n' + ''.join(
        json.dumps(k, ensure_ascii=False) + ' = ' + json.dumps(v, ensure_ascii=False) + ';\n' for k,v in sorted(values.items())))

for column, language in enumerate(LANGUAGES):
    folder = ROOT / 'Shared/Resources' / (language + '.lproj')
    write_strings(folder / 'Localizable.strings', {k:v[column] for k,v in translations.items()})
    write_strings(folder / 'InfoPlist.strings', {'CFBundleDisplayName':'ArkCam', **{k:translations[v][column] for k,v in privacy.items()}})

(ROOT / 'scripts/localization/coverage.json').write_text(json.dumps({
    'languages': LANGUAGES, 'keys': len(translations),
    'presentationAliases': aliases,
    'nonUIExclusions': {keys[i]: 'URL, stable export basename, or software metadata' for i in sorted(excluded)},
}, ensure_ascii=False, indent=2) + '\n')
print(f'Generated {len(translations)} strings + {len(privacy)} permission descriptions in {len(LANGUAGES)} languages.')
